version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: athiraakhil16/dockerpoc
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9010:8080"
    networks:
      - webnet
networks:
  webnet: